// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4rbJCZdOYMYiCIfBkXrt__WdnwVglm_g',
    appId: '1:101282996198:web:2e052e1b57d69215270027',
    messagingSenderId: '101282996198',
    projectId: 'pondok-app-23ae1',
    authDomain: 'pondok-app-23ae1.firebaseapp.com',
    storageBucket: 'pondok-app-23ae1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdNynIVZJPIDgnird87mh0rSinsVUsbjQ',
    appId: '1:101282996198:android:556ab4da1deb909a270027',
    messagingSenderId: '101282996198',
    projectId: 'pondok-app-23ae1',
    storageBucket: 'pondok-app-23ae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3SXFyAE9IvCHqv3RVcHAUkPzf_TvDihQ',
    appId: '1:101282996198:ios:85efbc1389ace132270027',
    messagingSenderId: '101282996198',
    projectId: 'pondok-app-23ae1',
    storageBucket: 'pondok-app-23ae1.appspot.com',
    iosClientId: '101282996198-3t9i40548pte1jb94gc6231gkq4lf78r.apps.googleusercontent.com',
    iosBundleId: 'com.example.pondokApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3SXFyAE9IvCHqv3RVcHAUkPzf_TvDihQ',
    appId: '1:101282996198:ios:85efbc1389ace132270027',
    messagingSenderId: '101282996198',
    projectId: 'pondok-app-23ae1',
    storageBucket: 'pondok-app-23ae1.appspot.com',
    iosClientId: '101282996198-3t9i40548pte1jb94gc6231gkq4lf78r.apps.googleusercontent.com',
    iosBundleId: 'com.example.pondokApp',
  );
}
